spring:
  application:
    name: gateway-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8000/realms/realm-name}
  cloud:
    gateway:
      routes:
      - id: user-service-route
        uri: lb://user-service
        predicates:
          - Path=/api/v1/users/**,/user-service-doc/**
      - id: salon-service-route
        uri: lb://salon-service
        predicates:
          - Path=/api/v1/salons/**,/salon-service-doc/**
      - id: category-service-route
        uri: lb://category-service
        predicates:
          - Path=/api/v1/categories/**,/category-service-doc/**
      - id: service-offering-service-route
        uri: lb://serviceoffering-service
        predicates:
          - Path=/api/v1/salonservices/**,/serviceoffering-service-doc/**
      - id: review-service-route
        uri: lb://review-service
        predicates:
          - Path=/api/v1/reviews/**,/review-service-doc/**
      - id: booking-service-route
        uri: lb://booking-service
        predicates:
          - Path=/api/v1/bookings/**,/booking-service-doc/**
      - id: payment-service-route
        uri: lb://payment-service
        predicates:
          - Path=/api/v1/payments/**,/payment-service-doc/**
      - id: notification-service-route
        uri: lb://notification-service
        predicates:
          - Path=/api/v1/notifications/**,/notification-service-doc/**

server:
  port: ${SERVER_PORT:8080} # Default gateway port, override with SERVER_PORT env var

eureka:
  client:
    register-with-eureka: true # This is Eureka client and it needs to register with Eureka server default is true
    fetch-registry: true # This is Eureka client and it need to fetch registry from eureka server default is true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus # Expose Actuator endpoints
  endpoint:
    health:
      show-details: always
    prometheus:
     access: unrestricted
  server:
    port: ${MANAGEMENT_SERVER_PORT:9000}
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      instance: ${INSTANCE_ID:default-instance}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}

springdoc:
  swagger-ui:
    urls:
      - name: User Service
        url: /user-service-doc/v3/api-docs
      - name: Salon Service
        url: /salon-service-doc/v3/api-docs
      - name: Category Service
        url: /category-service-doc/v3/api-docs
      - name: Salon Service Offering Service
        url: /serviceoffering-service-doc/v3/api-docs
      - name: Rview Service
        url: /review-service-doc/v3/api-docs
      - name: Booking Service
        url: /booking-service-doc/v3/api-docs
      - name: Payment Service
        url: /payment-service-doc/v3/api-docs
      - name: Notification Service
        url: /notification-service-doc/v3/api-docs
    oauth:
      client-id: ${SWAGGER_CLIENT_ID:clientId}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}