spring:
  application:
    name: eureka-server

server:
  port: ${SERVER_PORT:8761} # Default Eureka port, override with SERVER_PORT
  ssl:
    enabled: true # Enable HTTPS
    key-store: ${KEYSTORE_PATH:classpath:keystore.p12} # Override with KEYSTORE_PATH
    key-store-password: ${KEYSTORE_PASSWORD:changeit} # Override with KEYSTORE_PASSWORD
    key-store-type: PKCS12

eureka:
  user:
    name: ${EUREKA_USERNAME:username} # Override with EUREKA_USERNAME env var
    password: ${EUREKA_PASSWORD:password} # Override with EUREKA_PASSWORD env var
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:false} # Register with other Eureka servers in a cluster
    fetch-registry: ${FETCH_REGISTRY:false} # Fetch registry for clustering
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
      # For clustering, list peer URLs via env var or config
      # Example: https://eureka1.example.com:8761/eureka/,https://eureka2.example.com:8762/eureka/
  instance:
    hostname: ${EUREKA_HOSTNAME:eureka-server.example.com} # Override with EUREKA_HOSTNAME
    appname: eureka-cluster
    prefer-ip-address: true # Use IP in dynamic environments (Docker/K8s)
    lease-renewal-interval-in-seconds: 30 # Heartbeat interval
    lease-expiration-duration-in-seconds: 90 # Time before instance is removed
  server:
    enable-self-preservation: true # Enabled for reliability in production
    eviction-interval-timer-in-ms: 60000 # Standard eviction interval (60s)
    renewal-percent-threshold: 0.85 # Default threshold for self-preservation
    peer-node-read-timeout-ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus # Expose Actuator endpoints
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  server:
    port: ${MANAGEMENT_SERVER_PORT:8999}
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      instance: ${INSTANCE_ID:default-instance}

logging:
  level:
    '[com.netflix.eureka]': INFO # Less verbose logging in production
    '[org.springframework]': INFO