spring:
  application:
    name: payment-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/paymentservicedb}
    username: ${DATASOURCE_USERNAME:username}
    password: ${DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Automatically updates the schema (useful for development)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8000/realms/realm-name}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
          
server:
  port: ${SERVER_PORT:8087} #  override with SERVER_PORT env var
  forward-headers-strategy: framework

eureka:
  client:
    register-with-eureka: true # This is Eureka client and it needs to register with Eureka server default is true
    fetch-registry: true # This is Eureka client and it need to fetch registry from eureka server default is true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus # Expose Actuator endpoints
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  server:
    port: ${MANAGEMENT_SERVER_PORT:9007}
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      instance: ${INSTANCE_ID:default-instance}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}

springdoc:
  api-docs:
    path: /payment-service-doc/v3/api-docs
  swagger-ui:
    enabled: false

openid:
  connect:
    url: ${OPENID_CONNECT_URL:http://openidconnecturl}

stripe:
  api-key: ${STRIPE_SECRET_KEY:key}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET_KEY:key}
  frontend-success-url: ${STRIPE_PAYMENT_SUCCESS_URL:http://localhost}
  frontend-cancel-url: ${STRIPE_PAYMENT_CANCEL_URL:http://localhost}