spring:
  application:
    name: salon-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/salonservicedb}
    username: ${DATASOURCE_USERNAME:username}
    password: ${DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically updates the schema (useful for development)
    show-sql: true # Log SQL queries to the console
    properties:
      hibernate:
        '[format_sql]': true # Format SQL for better readability
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8000/realms/realm-name}
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 1000
            loggerLevel: basic
      circuitbreaker:
        enabled: false
          
resilience4j:
  circuitbreaker:
    instances:
      UserServiceCall:
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 60000
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
    circuit-breaker-aspect-order: 1
  retry:
    instances:
      UserServiceCall:
        maxAttempts: 2
        waitDuration: 5000
    retry-aspect-order: 2 

server:
  port: ${SERVER_PORT:8082} #  override with SERVER_PORT env var
  forward-headers-strategy: framework

eureka:
  client:
    register-with-eureka: true # This is Eureka client and it needs to register with Eureka server default is true
    fetch-registry: true # This is Eureka client and it need to fetch registry from eureka server default is true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents # Expose Actuator endpoints
  endpoint:
    health:
      show-details: always
  server:
    port: ${MANAGEMENT_SERVER_PORT:9002}

salon:
  image:
    upload:
      dir: ${SALON_IMAGE_UPLOAD_DIR:/data/uploads/salon-images/}
    url-prefix: ${SALON_IMAGE_URL_PREFIX:/salons/auth/images/}

springdoc:
  api-docs:
    path: /salon-service-doc/v3/api-docs
  swagger-ui:
    enabled: false

openid:
  connect:
    url: ${OPENID_CONNECT_URL:http://openidconnecturl}